# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19bef539353a2f5b89ad9474b2740ef870cccfb7ab403b5ce1a7fa623e9036a86ef4b8191515b98066a4d3766524e618b66cb6d130fd22b569feeea82acae6fd

test:
  secret_key_base: a7c885a6d570d0bd80c6ea2f218c12adb02c5522ee06b5e04531f628c64d82b79aebdfb9d4ad2faa69b0d523caa4d52c71355888ec90dcbfd82fa2266417d579

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
